--- 
apiVersion: config.istio.io/v1alpha2
kind: EndUserAuthenticationPolicySpec
metadata: 
  name: httpbin-auth-policy
  namespace: tutorial
spec: 
  jwts: 
    - issuer: http://keycloak:8080/auth/realms/istio
      jwks_uri: http://keycloak.tutorial:8080/auth/realms/istio/protocol/openid-connect/certs
      audiences: 
      - cars-web     
--- 
apiVersion: config.istio.io/v1alpha2
kind: EndUserAuthenticationPolicySpecBinding
metadata:
  name: httpbin-auth-policy-binding
  namespace: tutorial
spec:
  policies:
    - name: httpbin-auth-policy
      namespace: tutorial
  services:
    - name: httpbin
      namespace: tutorial